import pandas as pd
import io
from fpdf import FPDF

class AmbulancePDF(FPDF):
    def header(self):
        self.set_font('Arial', 'B', 14)
        self.set_fill_color(0, 51, 141)  # KPMG Blue
        self.set_text_color(255, 255, 255)
        self.cell(0, 12, '  Jharkhand 108 Ambulance Health Report', 0, 1, 'L', fill=True)
        self.ln(5)
        self.set_text_color(0, 0, 0)

    def footer(self):
        self.set_y(-15)
        self.set_font('Arial', 'I', 8)
        self.set_text_color(128, 128, 128)
        self.cell(0, 10, f'Page {self.page_no()}/{{nb}} | Generated by 108 Fleet Control System', 0, 0, 'C')

def generate_pdf(amb_data, instrument_cols):
    """Generates a professional PDF for a specific ambulance."""
    pdf = AmbulancePDF()
    pdf.alias_nb_pages()
    pdf.add_page()
    
    # Vehicle Info Section
    pdf.set_font('Arial', 'B', 12)
    pdf.set_fill_color(240, 240, 240)
    pdf.cell(0, 8, 'VEHICLE INFORMATION', 0, 1, 'L', fill=True)
    pdf.ln(3)
    
    pdf.set_font('Arial', '', 11)
    info_items = [
        ('Vehicle ID', amb_data.get('VEHICLE DEITALS', 'N/A')),
        ('District', amb_data.get('DISTRICT', 'N/A')),
        ('Vehicle Type', amb_data.get('TYPE OF VEHICLE', 'N/A')),
        ('Health Score', f"{amb_data.get('Health %', 0)}%"),
        ('Risk Status', amb_data.get('Risk Level', 'N/A')),
        ('EMT Name/ID', amb_data.get('EMT NAME / ID', 'Not Specified')),
    ]
    
    for label, value in info_items:
        pdf.set_font('Arial', 'B', 10)
        pdf.cell(50, 7, f'{label}:', 0)
        pdf.set_font('Arial', '', 10)
        pdf.cell(0, 7, str(value)[:80], 0, 1)
    
    pdf.ln(5)
    
    # Instrument Table
    pdf.set_font('Arial', 'B', 11)
    pdf.set_fill_color(0, 51, 141)
    pdf.set_text_color(255, 255, 255)
    pdf.cell(110, 8, '  Equipment Name', 1, 0, 'L', fill=True)
    pdf.cell(50, 8, '  Status', 1, 1, 'L', fill=True)
    
    pdf.set_text_color(0, 0, 0)
    pdf.set_font('Arial', '', 9)
    
    for idx, inst in enumerate(instrument_cols):
        status = str(amb_data.get(inst, 'N/A')).strip().upper()
        
        # Alternate row colors
        if idx % 2 == 0:
            pdf.set_fill_color(248, 248, 248)
        else:
            pdf.set_fill_color(255, 255, 255)
        
        pdf.cell(110, 7, f'  {str(inst)[:55]}', 1, 0, 'L', fill=True)
        
        # Color status
        if status == 'WORKING':
            pdf.set_text_color(0, 128, 0)
        elif status == 'NOT WORKING':
            pdf.set_text_color(200, 0, 0)
        else:
            pdf.set_text_color(128, 128, 128)
        
        pdf.cell(50, 7, f'  {status}', 1, 1, 'L', fill=True)
        pdf.set_text_color(0, 0, 0)
    
    return bytes(pdf.output(dest='S'))


def generate_excel_report(df_filtered, missing_ids=None, fleet_analysis=None, dist_summary=None, type_summary=None, equipment_failures=None, inst_cols=None, master=None):
    """Generates a professional multi-sheet Excel report equivalent to the dashboard tabs."""
    output = io.BytesIO()
    with pd.ExcelWriter(output, engine='xlsxwriter') as writer:
        workbook = writer.book
        
        # Define formats
        header_fmt = workbook.add_format({
            'bold': True, 'bg_color': '#00338D', 'font_color': 'white',
            'border': 1, 'font_size': 11, 'align': 'center', 'valign': 'vcenter'
        })
        title_fmt = workbook.add_format({
            'bold': True, 'font_size': 14, 'font_color': '#00338D',
            'bottom': 2, 'bottom_color': '#00338D'
        })
        metric_label_fmt = workbook.add_format({
            'bold': True, 'font_size': 11, 'bg_color': '#F0F4FF', 'border': 1
        })
        metric_val_fmt = workbook.add_format({
            'font_size': 11, 'border': 1, 'num_format': '0.00'
        })
        danger_fmt = workbook.add_format({
            'bg_color': '#FFE0E0', 'font_color': '#CC0000', 'border': 1
        })
        success_fmt = workbook.add_format({
            'bg_color': '#E0FFE0', 'font_color': '#006600', 'border': 1
        })
        
        # ========= SHEET 1: Fleet Overview =========
        overview = workbook.add_worksheet('Fleet_Overview')
        overview.set_column('A:A', 35)
        overview.set_column('B:B', 25)
        overview.set_column('C:C', 20)
        
        overview.write('A1', 'JHARKHAND 108 AMBULANCE DASHBOARD: FLEET OVERVIEW', title_fmt)
        
        total_reported = len(df_filtered)
        avg_health = round(df_filtered['Health %'].mean(), 2) if total_reported > 0 else 0
        high_risk = len(df_filtered[df_filtered['Risk Level'] == 'High Risk'])
        med_risk = len(df_filtered[df_filtered['Risk Level'] == 'Medium Risk'])
        low_risk = len(df_filtered[df_filtered['Risk Level'] == 'Low Risk'])
        
        overview.write('A3', 'Total Vehicles Reported', metric_label_fmt)
        overview.write('B3', total_reported, metric_val_fmt)
        overview.write('A4', 'Average Operational Health (%)', metric_label_fmt)
        overview.write('B4', avg_health, metric_val_fmt)
        overview.write('A5', 'High Risk Vehicles', metric_label_fmt)
        overview.write('B5', high_risk, danger_fmt)
        overview.write('A6', 'Medium Risk Vehicles', metric_label_fmt)
        overview.write('B6', med_risk, metric_val_fmt)
        overview.write('A7', 'Low Risk Vehicles (Functional)', metric_label_fmt)
        overview.write('B7', low_risk, success_fmt)
        overview.write('A8', 'Missing / Unreported Vehicles', metric_label_fmt)
        overview.write('B8', len(missing_ids) if missing_ids else 0, danger_fmt if missing_ids else metric_val_fmt)
        
        # Risk Pie Chart
        chart_data = workbook.add_worksheet('_Chart_Overview')
        risk_counts = df_filtered['Risk Level'].value_counts()
        chart_data.write_column('A1', risk_counts.index)
        chart_data.write_column('B1', risk_counts.values)
        
        pie = workbook.add_chart({'type': 'pie'})
        pie.add_series({
            'name': 'Risk Distribution',
            'categories': ['_Chart_Overview', 0, 0, len(risk_counts)-1, 0],
            'values': ['_Chart_Overview', 0, 1, len(risk_counts)-1, 1],
            'points': [
                {'fill': {'color': '#E74C3C'}},
                {'fill': {'color': '#F5A623'}},
                {'fill': {'color': '#00A651'}},
            ]
        })
        pie.set_title({'name': 'Operational Risk Distribution'})
        pie.set_size({'width': 480, 'height': 320})
        overview.insert_chart('E3', pie)
        
        # Immediate Audit Table
        overview.write('A11', 'VEHICLES REQUIRING IMMEDIATE AUDIT (High/Medium Risk)', title_fmt)
        audit_df = df_filtered[df_filtered['Risk Level'] != 'Low Risk'].sort_values('Health %')
        if len(audit_df) > 0:
            audit_display = audit_df[['VEHICLE DEITALS', 'DISTRICT', 'TYPE OF VEHICLE', 'Risk Level', 'Health %']]
            audit_display.to_excel(writer, sheet_name='Fleet_Overview', startrow=12, index=False)
            
            # Format headers
            for col_num, val in enumerate(audit_display.columns.values):
                overview.write(12, col_num, val, header_fmt)
                overview.set_column(col_num, col_num, 20)
        else:
            overview.write('A13', 'All vehicles are in Low Risk category (Health > 80%).')
            
        
        # ========= SHEET 2: District Analysis =========
        if dist_summary is not None:
            dist_sheet = workbook.add_worksheet('District_Analysis')
            dist_sheet.write('A1', 'DISTRICT-WISE VEHICLE COMPARISON', title_fmt)
            
            # Write data
            dist_summary.to_excel(writer, sheet_name='District_Analysis', startrow=2, index=False)
            
            # Format Header & Columns
            for col_num, val in enumerate(dist_summary.columns.values):
                dist_sheet.write(2, col_num, val, header_fmt)
                dist_sheet.set_column(col_num, col_num, 16)
                
            # Chart: Total vs Functional Vehicles
            dist_chart_data = workbook.add_worksheet('_Chart_District')
            num_dists = len(dist_summary)
            dist_chart_data.write_column('A1', dist_summary['DISTRICT'])
            dist_chart_data.write_column('B1', dist_summary['Total_Vehicles'])
            dist_chart_data.write_column('C1', dist_summary['Functional_Vehicles'])
            
            bar_chart = workbook.add_chart({'type': 'column'})
            bar_chart.add_series({
                'name': 'Total Reported Vehicles',
                'categories': ['_Chart_District', 0, 0, num_dists-1, 0],
                'values': ['_Chart_District', 0, 1, num_dists-1, 1],
                'fill': {'color': '#00338D'}
            })
            bar_chart.add_series({
                'name': 'Functional (Low Risk)',
                'categories': ['_Chart_District', 0, 0, num_dists-1, 0],
                'values': ['_Chart_District', 0, 2, num_dists-1, 2],
                'fill': {'color': '#00A651'}
            })
            bar_chart.set_title({'name': 'Total vs Functional Vehicles by District'})
            bar_chart.set_x_axis({'name': 'District'})
            bar_chart.set_y_axis({'name': 'Count'})
            bar_chart.set_size({'width': 700, 'height': 400})
            
            dist_sheet.insert_chart('J3', bar_chart)


        # ========= SHEET 3: Vehicle Types =========
        if type_summary is not None:
            types_sheet = workbook.add_worksheet('Vehicle_Types')
            types_sheet.write('A1', 'VEHICLE TYPE ANALYSIS', title_fmt)
            
            type_summary.to_excel(writer, sheet_name='Vehicle_Types', startrow=2, index=False)
            for col_num, val in enumerate(type_summary.columns.values):
                types_sheet.write(2, col_num, val, header_fmt)
                types_sheet.set_column(col_num, col_num, 18)
                
            # Pie Chart Fleet Mix
            num_types = len(type_summary)
            type_data = workbook.add_worksheet('_Chart_Types')
            type_data.write_column('A1', type_summary['TYPE OF VEHICLE'])
            type_data.write_column('B1', type_summary['Count'])
            
            mix_pie = workbook.add_chart({'type': 'pie'})
            mix_pie.add_series({
                'name': 'Fleet Mix',
                'categories': ['_Chart_Types', 0, 0, num_types-1, 0],
                'values': ['_Chart_Types', 0, 1, num_types-1, 1],
            })
            mix_pie.set_title({'name': 'Fleet Composition by Type'})
            mix_pie.set_size({'width': 480, 'height': 320})
            types_sheet.insert_chart('G3', mix_pie)


        # ========= SHEET 4: Equipment Failures =========
        if equipment_failures is not None:
            fails_sheet = workbook.add_worksheet('Equipment_Failures')
            fails_sheet.write('A1', 'EQUIPMENT FAILURE MATRIX', title_fmt)
            
            equipment_failures.to_excel(writer, sheet_name='Equipment_Failures', startrow=2, index=False)
            for col_num, val in enumerate(equipment_failures.columns.values):
                fails_sheet.write(2, col_num, val, header_fmt)
                fails_sheet.set_column(col_num, col_num, 22)
            
            # Top 15 Failures Chart (Bar)
            fail_data = workbook.add_worksheet('_Chart_Fail')
            top_fails = equipment_failures.head(15)
            fail_data.write_column('A1', top_fails['Instrument'])
            fail_data.write_column('B1', top_fails['Not Working'])
            
            fail_bar = workbook.add_chart({'type': 'bar'})
            fail_bar.add_series({
                'name': 'Failures',
                'categories': ['_Chart_Fail', 0, 0, min(14, len(top_fails)-1), 0],
                'values': ['_Chart_Fail', 0, 1, min(14, len(top_fails)-1), 1],
                'fill': {'color': '#E74C3C'}
            })
            fail_bar.set_title({'name': 'Top Equipment Failures'})
            fail_bar.set_y_axis({'reverse': True})
            fail_bar.set_size({'width': 600, 'height': 450})
            fails_sheet.insert_chart('F3', fail_bar)
            

        # ========= SHEET 5: Fleet Coverage & Missing =========
        if fleet_analysis:
            fleet_sheet = workbook.add_worksheet('Fleet_Coverage')
            fleet_sheet.write('A1', 'FLEET COVERAGE & MISSING ANALYSIS', title_fmt)
            
            status_items = [
                ('Total Fleet Size', fleet_analysis['total_fleet']),
                ('On-Road (HOTO Done)', fleet_analysis['by_status'].get('On-Road (HOTO Done)', 0)),
                ('Under CS Repair', fleet_analysis['by_status'].get('Under CS Repair', 0)),
                ('Pending from EMRI', fleet_analysis['by_status'].get('Pending from EMRI', 0)),
                ('HOTO Pending', fleet_analysis['by_status'].get('HOTO Pending', 0)),
            ]
            for i, (label, val) in enumerate(status_items):
                fleet_sheet.write(i + 2, 0, label, metric_label_fmt)
                fleet_sheet.write(i + 2, 1, val, metric_val_fmt)
            
            fleet_sheet.set_column('A:A', 30)
            fleet_sheet.set_column('B:B', 15)
            
            # Missing vehicles table (with EMT Name if possible)
            fleet_sheet.write('A10', f'MISSING / UNREPORTED VEHICLES ({len(missing_ids)} Total)', title_fmt)
            
            missing_cols = ['Vehicle ID', 'District', 'Fleet Status', 'Vehicle Type', 'Base Location', 'EMT Name / ID']
            for ci, cname in enumerate(missing_cols):
                fleet_sheet.write(11, ci, cname, header_fmt)
                fleet_sheet.set_column(ci, ci, 20)
                
            if missing_ids and len(missing_ids) > 0:
                master_proc = fleet_analysis['processed_df']
                # Try to find EMT column from raw master data if it exists
                emt_col_master = None
                if master is not None:
                    for col in master.columns:
                        if 'EMT' in col.upper() or 'PILOT' in col.upper():
                            emt_col_master = col
                            break
                            
                for i, mid in enumerate(missing_ids):
                    row_num = i + 12
                    fleet_sheet.write(row_num, 0, mid, danger_fmt)
                    
                    match = master_proc[master_proc['VEHICLE_ID'].str.upper() == mid.upper()]
                    if len(match) > 0:
                        fleet_sheet.write(row_num, 1, match.iloc[0].get('DISTRICT', 'N/A'))
                        fleet_sheet.write(row_num, 2, match.iloc[0].get('Fleet Status', 'Unknown'))
                        fleet_sheet.write(row_num, 3, match.iloc[0].get('VEHICLE_TYPE', 'N/A'))
                        fleet_sheet.write(row_num, 4, match.iloc[0].get('BASE LOCATION', 'N/A'))
                        
                        # Fetch EMT name if available in master data
                        emt_val = 'N/A'
                        if emt_col_master and master is not None:
                            raw_match = master[master.iloc[:, 0].astype(str).str.contains(mid, na=False, case=False)]
                            if len(raw_match) > 0:
                                emt_val = str(raw_match.iloc[0].get(emt_col_master, 'N/A'))
                        fleet_sheet.write(row_num, 5, emt_val)
                    else:
                        fleet_sheet.write(row_num, 1, 'N/A')
                        fleet_sheet.write(row_num, 2, 'N/A')
                        fleet_sheet.write(row_num, 3, 'N/A')
                        fleet_sheet.write(row_num, 4, 'N/A')
                        fleet_sheet.write(row_num, 5, 'N/A')
        else:
            # Simple missing vehicles if fleet_analysis unavailable
            missing_sheet = workbook.add_worksheet('Missing_Vehicles')
            missing_sheet.write('A1', f'MISSING / UNREPORTED VEHICLES ({len(missing_ids)} Total)', title_fmt)
            missing_sheet.write('A3', 'Vehicle ID', header_fmt)
            missing_sheet.write('B3', 'Report Status', header_fmt)
            missing_sheet.set_column('A:B', 25)
            if missing_ids:
                for i, mid in enumerate(missing_ids):
                    missing_sheet.write(i + 3, 0, mid, danger_fmt)
                    missing_sheet.write(i + 3, 1, 'Not Reported')


        # ========= SHEET 6: Full Data Logs =========
        df_filtered.to_excel(writer, index=False, sheet_name='Dashboard_Raw_Data')
        
        # Hide internal chart data sheets
        try:
            workbook.get_worksheet_by_name('_Chart_Overview').hide()
            workbook.get_worksheet_by_name('_Chart_District').hide()
            workbook.get_worksheet_by_name('_Chart_Types').hide()
            workbook.get_worksheet_by_name('_Chart_Fail').hide()
        except:
            pass
            
    return output.getvalue()
